### ISSUE TITLE
Support for Sway WM

### ISSUE THREAD

**Issue by ramazanemreosmanoglu** [GitGangGuy/dynamic-wallpaper-improved#3]
Hi!

Sway WM uses a command called swaybg for setting wallpapers. For example:

```
swaybg -i /path/to/image
```

But this command don't starts another process like feh.

**Comment by GitGangGuy** [comment]
Fixed in 109312c10a1cb6b430fe31ddc8bea46cbdafcfde. Let me know if that doesn't work! :smile:
