### ISSUE TITLE
Can't get my background to change with dwall

### ISSUE THREAD

**Issue by GooseLander** [GitGangGuy/dynamic-wallpaper-improved#4]
Hi, I am new to linux in general. I have been trying to use dwall but it won't work. I have Ubuntu 20.04 LTS

Whenever I try `dwall -s [style]` the background doesn't change at all! but when I use `dwall -p -b [backend] -s [style]` it actually works for the terminal, it changes the colors for it... Just the background never changes. Any idea on how I can fix this?

edit: I did some more digging and found out that the script does it job! I tried `gsettings get org.gnome.desktop.background picture-uri`
`'file:///usr/share/dynamic-wallpaper/images/beach/19.jpg'`

it shows what I chose as background, but the background still doesn't change at all for me.

**Comment by GooseLander** [comment]
nevermind! I found the fix, because I had installed anaconda3 it seems like the gsettings from there was interfering with gnome's main settings or something, I renamed the file in ~/.anaconda3/bin/gsettings to ~/.anaconda3/bin/gsettings_old
that fixed it for me.

**Comment by GitGangGuy** [comment]
Alright, let me know if something doesn't work again! Apparently GitHub failed to send me a notification when you opened the issue (or I accidentally dismissed it) :unamused:
